### ISSUE TITLE
ctrl+d on FileTree node deletes node, but not file

### ISSUE THREAD

**Issue by rcoreilly** [goki/gide#84]
and in general need to update shortcuts for tree

**Comment by rohrlich** [comment]
I'll do this if you haven't done it already

**Comment by rcoreilly** [comment]
great!  good one.  also take a look at these while you're in there:

* https://github.com/goki/gi/issues/216  

* another one that I can't seem to find, about making those actions e.g., delete, rename go through version control commands if VCS is active (git, svn etc). probably cleanest to just move the VCS stuff into gi -- would be generally useful for all such filetree functionality to be VCS aware.  Then can just set the VCS state etc on the FileTree root node or something like that, if it detects a .git file etc.  Logic is all already in gide, just need to move it and apply it..

**Comment by rohrlich** [comment]
I have this working but this is a case I dare not check it in without your input. The problem is that the key events are going to giv.treeview. It seems that what we need is to implement event handling in gide.filetree and that is what I did. And then in the case of delete call FileTreeView.DeleteFiles() which is what is called from the context menu when delete is selected. I'm thinking that if the context menu works then there is some other fix that might work without implementing event handling in gide.filetree.

**Comment by rcoreilly** [comment]
Context menu items can't establish shortcuts by themselves I think, so yeah I think just implementing the key input is what is needed.  However, to make it more general, would be best to impl most of it in giv.FileTreeView to handle the base cases that are impl there, and then gide.FileTreeView can call that and handle its special cases. You can also add the key-based shortcuts to the ContextMenuActive properties for both, so the shortcuts are visible.

**Comment by rcoreilly** [comment]
ps. Ctrl+O = insert after could be used for New FOlder and Ctrl+I = insert before -> New FIle

**Comment by rohrlich** [comment]
All handled by giv.FileTreeView. Shortcuts added
