### ISSUE TITLE
Comments on new Symbols tab 

### ISSUE THREAD

**Issue by rohrlich** [goki/gide#97]
The structure button on the toolbar opens the "structure" tab to display clickable links to the active files functions. Pretty ugly but it is a very convenient way to get around a file or browse its functions. GoLand also displays vars, types, etc. and we could have checkboxes at the top of the structure view to turn these on/off. I find the function links are what I really use a lot so that is what I implemented. GoLand also has a checkbox for "package" and the you get a structure view of the package instead of just the active file. At the moment you need to click on the toolbar to update the view but it would make sense to do the same for clicking the tab. And it might make sense to just update automatically when the active view changes if the structure tab is the selected tab. Really need to do something about the look at some point :)

**Comment by rohrlich** [comment]
Functions with different receivers are indistinguishable as currently displayed.

**Comment by rcoreilly** [comment]
I fixed parser to add the receiver detail -- is the first non-paren-enclosed text in detail -- you'll need to update the formatting. also should add some sorting :)  Looks very useful overall -- might as well add the types and vars etc in diff sections.  probably want to sort by type so that all the stuff for a given type is all in one section, with the main struct or whatever defn and then all the methods for it, etc.

**Comment by rohrlich** [comment]
Yes, will do all of that.

**Comment by rcoreilly** [comment]
btw probably makes sense to just directly access the FileState.Syms in gide, instead of going through the whole lang interface -- symbols should be generic enough.  also you can use the method that sorts by kind and then name -- see the WriteDoc example:

// WriteDoc writes basic doc info, sorted by kind and name
func (sm *SymMap) WriteDoc(out io.Writer, depth int) {
	nms := sm.KindNames(true)
	for _, nm := range nms {
		ci := strings.Index(nm, ":")
		sy := (*sm)[nm[ci+1:]]
		sy.WriteDoc(out, depth)
	}
}

**Comment by rohrlich** [comment]
Now called Symbols instead of Structure. Implementing as a treeview instead of text, much better! (not checked in yet)
